### ISSUE TITLE
System perl used in tests

### ISSUE THREAD

**Issue by eserte** [benkasminbullock/json-create#46]
t/zz-pure-perl.t fails on most of my smokers, for example like this:
```
Can't locate JSON/Parse.pm in @INC (you may need to install the JSON::Parse module) (@INC contains: /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/t/../blib/arch /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/t/../blib/lib /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/blib/lib /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/blib/arch /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.22.1 /usr/local/share/perl/5.22.1 /usr/lib/x86_64-linux-gnu/perl5/5.22 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.22 /usr/share/perl/5.22 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/t/../t/bool.t line 13.
BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/t/../t/bool.t line 13.
...
BEGIN failed--compilation aborted at /home/cpansand/.cpan/build/2021020922/JSON-Create-0.30_04-1/t/../t/write-json.t line 13.

#   Failed test 'passed tests'
#   at t/zz-pure-perl.t line 27.
# Looks like you failed 1 test of 1.
t/zz-pure-perl.t .... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests
```
It seems that the perl picked here is the wrong one: the first perl in user's PATH which is the system perl, not the perl used to build + test the distribution. Without digging any further, often such situations may be fixed by using `$^X` or so.

**Comment by benkasminbullock** [comment]
Until this version zz-pure-perl.t (used to be xt/pp.t) was an author-only test. It's meant to run the whole suite of tests under the condition of "pure perl", simulating the XS module failing to load using an environment variable. It is using the "prove" command rather than "perl" directly in about line 24 of the file. It's probably quite complicated to get the version of prove which this was called with, so I think what I'll do is put this back to being an author-only test, since I need the other changes in the module.

It's unfortunate since I recently had a set of failures in a dependent module due to a bug in JSON::Create::PP which could have been solved had the thing been properly tested. It turns out that PP was in use on some systems.

**Comment by eserte** [comment]
This is how I get the path to the correct prove: https://github.com/eserte/Doit/blob/bb6e6c840fdfe23175ce70ec35505721ec92a2b4/Build.PL#L970-L988

**Comment by benkasminbullock** [comment]
Thank you. I've uploaded 0.30_05 with this to CPAN, let's see what happens.

**Comment by eserte** [comment]
0.30_05 looks much better.

**Comment by benkasminbullock** [comment]
Thank you. There seems to be a remaining problem with some of the tests but it's not related to this.
